In [1]:
!pip install yfinance==0.2.38
!pip install pandas==2.2.2
!pip install nbformat

Collecting yfinance==0.2.38
  Downloading yfinance-0.2.38-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (2.32.2)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (5.2.1)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (3.17.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance==0.2.38) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\kartv\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance==0.2.38) (2.5)
Requirement already satisfied: six>=1.9 in c:\users\kartv\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance==0.2.38) (1.16.0)
Requirement already satisfied: webencodings in c:\users\kartv\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance==0.2.38) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kartv\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance==0.2.38) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kartv\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance==0.2.38) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\kartv\anaconda3\lib\site-packages (from requests>=2.31->yfinance==0.2.38) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kartv\anaconda3\lib\site-packages (from requests>=2.31->yfinance==0.2.38) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kartv\anaconda3\lib\site-packages (from requests>=2.31->yfinance==0.2.38) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kartv\anaconda3\lib\site-packages (from requests>=2.31->yfinance==0.2.38) (2024.6.2)
Downloading yfinance-0.2.38-py2.py3-none-any.whl (72 kB)
   ---------------------------------------- 0.0/73.0 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/73.0 kB ? eta -:--:--
   ---------------------------------------  71.7/73.0 kB 991.0 kB/s eta 0:00:01
   ---------------------------------------- 73.0/73.0 kB 1.0 MB/s eta 0:00:00
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.41
    Uninstalling yfinance-0.2.41:
      Successfully uninstalled yfinance-0.2.41
Successfully installed yfinance-0.2.38
Requirement already satisfied: pandas==2.2.2 in c:\users\kartv\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kartv\anaconda3\lib\site-packages (from pandas==2.2.2) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kartv\anaconda3\lib\site-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kartv\anaconda3\lib\site-packages (from pandas==2.2.2) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kartv\anaconda3\lib\site-packages (from pandas==2.2.2) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\kartv\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.16.0)
Requirement already satisfied: nbformat in c:\users\kartv\anaconda3\lib\site-packages (5.9.2)
Requirement already satisfied: fastjsonschema in c:\users\kartv\anaconda3\lib\site-packages (from nbformat) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\kartv\anaconda3\lib\site-packages (from nbformat) (4.19.2)
Requirement already satisfied: jupyter-core in c:\users\kartv\anaconda3\lib\site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\kartv\anaconda3\lib\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\kartv\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\kartv\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\kartv\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\kartv\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (0.10.6)
Requirement already satisfied: platformdirs>=2.5 in c:\users\kartv\anaconda3\lib\site-packages (from jupyter-core->nbformat) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\kartv\anaconda3\lib\site-packages (from jupyter-core->nbformat) (305.1)

In [79]:
import warnings
# Ignore all warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [3]:
!pip install yfinance
!pip install bs4
!pip install nbformat

Requirement already satisfied: yfinance in c:\users\kartv\anaconda3\lib\site-packages (0.2.38)
Requirement already satisfied: pandas>=1.3.0 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (2.32.2)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (5.2.1)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (3.17.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in c:\users\kartv\anaconda3\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\kartv\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in c:\users\kartv\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\kartv\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kartv\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kartv\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\kartv\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kartv\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kartv\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kartv\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2024.6.2)
Collecting bs4
  Using cached bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in c:\users\kartv\anaconda3\lib\site-packages (from bs4) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\kartv\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Using cached bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2
Requirement already satisfied: nbformat in c:\users\kartv\anaconda3\lib\site-packages (5.9.2)
Requirement already satisfied: fastjsonschema in c:\users\kartv\anaconda3\lib\site-packages (from nbformat) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\kartv\anaconda3\lib\site-packages (from nbformat) (4.19.2)
Requirement already satisfied: jupyter-core in c:\users\kartv\anaconda3\lib\site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\kartv\anaconda3\lib\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\kartv\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\kartv\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\kartv\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\kartv\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat) (0.10.6)
Requirement already satisfied: platformdirs>=2.5 in c:\users\kartv\anaconda3\lib\site-packages (from jupyter-core->nbformat) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\kartv\anaconda3\lib\site-packages (from jupyter-core->nbformat) (305.1)

In [5]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [7]:
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = stock_data[stock_data.Date <= '2021--06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

In [11]:
tesla = yf.Ticker('TSLA')

In [19]:
tesla_data = tesla.history(period = 'max')
tesla_data.reset_index(inplace=True)
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [29]:
url = ' https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm'
html_data = requests.get(url).text
soup = BeautifulSoup(html_data, 'html.parser')

In [87]:
data = pd.read_html(url)
tesla_revenue = data[1]
tesla_revenue.columns = ['Date','Revenue']
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"", regex=True)
tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]
tesla_revenue.tail()

<>:4: SyntaxWarning: invalid escape sequence '\$'
<>:4: SyntaxWarning: invalid escape sequence '\$'
C:\Users\kartv\AppData\Local\Temp\ipykernel_25680\847713204.py:4: SyntaxWarning: invalid escape sequence '\$'
  tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"", regex=True)

          Date Revenue
48  2010-09-30      31
49  2010-06-30      28
50  2010-03-31      21
52  2009-09-30      46
53  2009-06-30      27

In [89]:
gme = yf.Ticker('GME')
gme_data = gme.history(period = 'max')
gme_data.reset_index(inplace=True)
gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658001,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615921,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [95]:
url = ' https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html'
html_data_2 = requests.get(url).text
soup = BeautifulSoup(html_data_2, 'html.parser')
data = pd.read_html(url)
gme_revenue = data[1]
gme_revenue.columns = ['Date','Revenue']
gme_revenue["Revenue"] = gme_revenue['Revenue'].str.replace(',|\$',"", regex=True)
gme_revenue.dropna(inplace=True)

gme_revenue = gme_revenue[gme_revenue['Revenue'] != ""]
gme_revenue.tail()

<>:7: SyntaxWarning: invalid escape sequence '\$'
<>:7: SyntaxWarning: invalid escape sequence '\$'
C:\Users\kartv\AppData\Local\Temp\ipykernel_25680\1128082035.py:7: SyntaxWarning: invalid escape sequence '\$'
  gme_revenue["Revenue"] = gme_revenue['Revenue'].str.replace(',|\$',"", regex=True)

          Date Revenue
57  2006-01-31    1667
58  2005-10-31     534
59  2005-07-31     416
60  2005-04-30     475
61  2005-01-31     709

In [ ]:
make_graph(tesla_data, tesla_revenue, 'Tesla')